---

- name: ensure packages are installed
  apt:
    update_cache: yes
    name: "{{item}}"
  with_items:
    - postgresql
    - libpq-dev
    - python3-psycopg2


- name: ensure database exists
  postgresql_db:
    name: "{{ netbox_database_name }}"
  become_user: postgres

- name: ensure database user exists
  postgresql_user:
    db: "{{ netbox_database_name }}"
    name: "{{ netbox_database_user }}"
    password: "{{ netbox_database_password }}"
    encrypted: yes
    priv: ALL
  become_user: postgres


